### ISSUE TITLE
Artifact Award Page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#34]
I have received emails from senior members of ASSETS talking about the ASSETS'22 Artifact Award.

https://assets21.sigaccess.org/artifacts.html
![image](https://user-images.githubusercontent.com/1621749/156653011-89390445-d688-439e-936d-ffd44a09c6a5.png)

- We need to engage the Best Artifact Chair, [Dragan Ahmetovic](http://dragan.ahmetovic.it/) (email: best-artifact-assets22@acm.org), and work on this page for ASSETS'22
- We need to figure out where/how we can get funding for the awards. Even if we can't get funding, I think we should still have the awards

**Comment by loopRW** [comment]
This is the draft of the content for **The Best Artifact Award** page:

--------------

## ASSETS 2022 Best Artifact Award

Since 2019, the ASSETS Conference spotlights submissions featuring publicly available artifacts, including apps, data sets, commercial products, or open-source projects. Among these works, the ASSETS Best Artifact Awards are assigned to the ones that most significantly contribute to the field of accessibility.


### Who is eligible for this award?

Authors of all submissions accepted at ASSETS 2022 that feature an artifact component are eligible. These include technical or workshop papers, posters, demos, experience reports, student research competition and doctoral consortium submissions.


### What counts as an artifact?

Eligible artifacts are research results, projects, products or items that can be downloaded, purchased, or accessed by the general public. Examples include apps in mobile or desktop app stores, physical devices that can be purchased, public data sets, or web apps that are publicly available.
Open-source projects are eligible if they include appropriate documentation and are presented in a form that can be used by a non-expert computer user.


### What is the benefit of participating in this program?

All applicants will be acknowledged in the ASSETS 2022 program, including links to each project. The Top-3 Artifacts will receive the following prizes:
- First place: $1000
- Second place: $500
- Third place: $250


### How will the winners be chosen?

The Top-3 Artifacts will be selected based on the project’s contribution to the field of accessibility. A combination of delegate voting (used to select the Top-5) and input from a panel of judges (selecting among the Top-5) will determine the winners.



### How to apply?

During the camera-ready submission process, the authors of accepted ASSETS 2022 submissions that wish to apply for the Best Artifact Award will be asked to provide a link to the publicly available artifact and a paragraph describing how it can benefit end-users, developers, and/or accessibility researchers.

**Comment by loopRW** [comment]
After the submissions deadline, after the first paragraph, the following content should be added (the last part should be a table as the previous year):

-----

### Delegate voting

During the conference, attendees can vote for their favorite items. You can also engage with the artifact authors on Discord via channels in the Abstract Award category.

**Link to vote for submissions (for conference attendees only)**

### Candidate submissions list:

Artifact name & ASSETS submission link | Submission type | Link to Artifact

**Comment by loopRW** [comment]
If there will be a general "Awards" page, it should include a pointer to the "The Best Artifact Award" page. The final line should be replaced with "ASSETS 2022 Best Artifact Award delegate voting is currently open at the **ASSETS 2022 Best Artifact Award page**", when the voting is available. If possible, this text could be replicated on the front page at that time.

------

### ASSETS 2022 Best Artifact Award

For the fourth year, the ASSETS Conference highlights submissions that include some component that is accessible to the public through the Best Artifact Award. This includes apps, data sets, commercial products, and open-sourced code with full documentation. Applicants must have an accepted paper, poster, demo, experience report or accepted student design competition submission related to the project at ASSETS 2021.

More information is available at the **ASSETS 2022 Best Artifact Award page**

**Comment by loopRW** [comment]
Once the awards are selected, the page should be updated. The table could be modified by adding an award column or prepending an image to the winning titles to highlight the 1st, 2nd and 3rd places. these should be placed in order from the top.

**Comment by judykong97** [comment]
<img width="1440" alt="Screen Shot 2022-04-29 at 11 35 42 PM" src="https://user-images.githubusercontent.com/15822762/166094826-df13bb30-329a-4c29-92cd-041fb897306e.png">
