### ISSUE TITLE
Please add Adobe logo as Gold sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#51]
This is the logo from Wikimedia. I'll follow-up with Adobe to see if we can get something official: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Adobe_Corporate_Logo.png/1200px-Adobe_Corporate_Logo.png

**Comment by ArkaneCow** [comment]
i went ahead and added adobe to the [sponsors page](https://assets22.sigaccess.org/sponsors.html) using the Wikimedia logo. i slightly adjusted the image with some padding so that it would be of similar width to the other logos on that page. if we get a new logo to use from adobe, I'm happy to update it.

**Comment by jonfroehlich** [comment]
Thanks. Looks great overall! I think probably we should make it a bit smaller since one of our advertising incentivizes to Champion sponsors is to have largest logo on our webpage :)

And the Adobe logo does look disproportionately large compared to, say, the Apple and Meta logos

![image](https://user-images.githubusercontent.com/1621749/169836462-6425bd4e-2853-4044-ae02-dc1cf45a6341.png)
